name: publish

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - uses: sigma/vsce-publish-action@v0.0.2
        with:
            vsce_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
